### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by BlackIQ** [ThevergeOn/React-todolist#2]
Application **insert** and **update** null items.

Add a function to check value or use built in functions to do that.

![Screenshot from 2022-03-12 16-58-42](https://user-images.githubusercontent.com/55284339/158019796-a491f7ec-0203-4962-b2e5-e707fc1b7b7e.png)
![Screenshot from 2022-03-12 16-58-31](https://user-images.githubusercontent.com/55284339/158019799-81c8879a-4c62-4480-b115-f18a8ab73cbc.png)

**Comment by BlackIQ** [comment]
You did it. Great.

**Comment by ThevergeOn** [comment]
Yeah Thanks

**Comment by ThevergeOn** [comment]
Hey :)
Thanks for your help
Can you help me about this bug?
I don't know exactly how i could do it

**Comment by BlackIQ** [comment]
Hi,

How are you?
How can I help you? You mean fixing null issue or is there anything else?

BTW, **GitHub comments** is not a messaging platform :)

**Comment by ThevergeOn** [comment]
Hi, I don't know exactly what it was, but I think I could did it myself
thank you

**Comment by BlackIQ** [comment]
ببخشید حقیقتا متوجه نشدم.
این مشکل نال رو منظورتونه؟ اوکی چشم من امروز عصر رفتم خونه انجام میدم.

حله.
